In [1]:
#*******************************************************************************************
 #
 #  File Name:  PyAviationAccidentsLoad.ipynb
 #
 #  File Description:
 #      This interactive Python notebook, PyAviationAccidentsLoad.ipynb, 
 #      uses loads all the aviation accident information into an sqlite
 #      database.
 #
 #
 #  Date            Description                             Programmer
 #  ----------      ------------------------------------    ------------------
 #  10/24/2023      Initial Development                     N. James George
 #
 #******************************************************************************************/

import PyFunctions as function
import PyLogFunctions as log_function
import PyLogSubRoutines as log_subroutine
import PySubRoutines as subroutine

import PyAviationAccidentsConstants as local_constant
import PyAviationAccidentsFunctions as local_function

import sqlite3

from sqlalchemy.ext.automap import automap_base
from sqlalchemy import create_engine, inspect

In [2]:
CONSTANT_LOCAL_FILE_NAME \
    = 'PyAviationAccidentsLoad.ipynb'

In [3]:
log_subroutine \
    .SetLogMode \
        (False)

log_subroutine \
    .SetDebugMode \
        (False)

log_subroutine \
    .SetImageMode \
        (False)


log_subroutine \
    .BeginProgramExecution \
        ('PyAviationAccidentsLoad')

# <br> **Section 1: Data Preparation**

## **1.1: Read CSV Files**

### **Aviation Accidents Database Table**

In [4]:
accidentsDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .AVIATION_ACCIDENTS_DATABASE_TABLE_CSV_FILE)

accidentsDataFrame \
    = accidentsDataFrame \
        .drop \
            (accidentsDataFrame.columns[0], 
             axis = 1)

accidentsDataFrame \
    ['country'] \
        .replace \
            ('United States of America', 
             'United States', 
             inplace = True)

accidentsDataFrame \
    = accidentsDataFrame \
        .fillna \
            ({'country_code': 
              'NA'})


log_function \
    .DebugReturnObjectWriteObject \
        (accidentsDataFrame)

### **Country Database Table**

In [5]:
countryDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .COUNTRY_DATABASE_TABLE_CSV_FILE)

countryDataFrame \
    = countryDataFrame \
        .rename \
            (columns \
                 = {'Unnamed: 0': 'id_number'})

countryDataFrame \
    [['region', 'subregion']] \
        = countryDataFrame[['region', 'subregion']] \
            .fillna \
                ('n/a')

countryDataFrame \
    ['country'] \
        .replace \
            ('United States of America', 
             'United States', 
             inplace = True)

countryDataFrame \
    ['country_code'] \
        .fillna \
            ('NA', 
             inplace = True)


log_function \
    .DebugReturnObjectWriteObject \
        (countryDataFrame)

### **Aircraft Types Database Table**

In [6]:
typesDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .AIRCRAFT_TYPES_DATABASE_TABLE_CSV_FILE)

typesDataFrame \
    = typesDataFrame \
        .rename \
            (columns \
                 = {'Unnamed: 0': 'id_number'})


log_function \
    .DebugReturnObjectWriteObject \
        (typesDataFrame)

### **Aircraft Operators Database Table**

In [7]:
operatorsDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .AIRCRAFT_OPERATORS_DATABASE_TABLE_CSV_FILE)

operatorsDataFrame \
    = operatorsDataFrame \
        .rename \
            (columns \
                 = {'Unnamed: 0': 'id_number'})


log_function \
    .DebugReturnObjectWriteObject \
        (operatorsDataFrame)

### **Aircraft Damage Database Table**

In [8]:
damageDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .AIRCRAFT_DAMAGE_DATABASE_TABLE_CSV_FILE)

damageDataFrame \
    = damageDataFrame \
        .rename \
            (columns \
                 = {'Unnamed: 0': 'id_number'})


log_function \
    .DebugReturnObjectWriteObject \
        (damageDataFrame)

### **Flight Phase Database Table**

In [9]:
phaseDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .FLIGHT_PHASE_DATABASE_TABLE_CSV_FILE)

phaseDataFrame \
    = phaseDataFrame \
        .rename \
            (columns \
                 = {'Unnamed: 0': 'id_number'})


log_function \
    .DebugReturnObjectWriteObject \
        (phaseDataFrame)

### **Nature of Flight Database Table**

In [10]:
natureDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .NATURE_OF_FLIGHT_DATABASE_TABLE_CSV_FILE)

natureDataFrame \
    = natureDataFrame \
        .rename \
            (columns \
                 = {'Unnamed: 0': 'id_number'})


log_function \
    .DebugReturnObjectWriteObject \
        (natureDataFrame)

### **Airports Database Table**

In [11]:
airportsDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .AIRPORTS_DATABASE_TABLE_CSV_FILE)

airportsDataFrame \
    = airportsDataFrame \
        .rename \
            (columns \
                 = {'Unnamed: 0': 'id_number'})


log_function \
    .DebugReturnObjectWriteObject \
        (airportsDataFrame)

### **Departure Airports Database Table**

In [12]:
departureDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .DEPARTURE_AIRPORTS_DATABASE_TABLE_CSV_FILE)

departureDataFrame \
    .drop \
        (columns \
             = departureDataFrame \
                 .columns[0], 
         axis = 1, 
         inplace = True)

departureDataFrame \
    ['country'] \
        .replace \
            ('United States of America', 
             'United States', 
             inplace = True)

departureDataFrame \
    ['country_code'] \
        .fillna \
            ('NA', 
             inplace = True)


log_function \
    .DebugReturnObjectWriteObject \
        (departureDataFrame)

### **Destination Airports Database Table**

In [13]:
destinationDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .DESTINATION_AIRPORTS_DATABASE_TABLE_CSV_FILE)

destinationDataFrame \
    .drop \
        (columns \
             = destinationDataFrame \
                .columns[0], 
         axis = 1, 
         inplace = True)

destinationDataFrame \
    ['country'] \
        .replace \
            ('United States of America', 
             'United States', 
             inplace = True)

destinationDataFrame \
    ['country_code'] \
        .fillna \
            ('NA', 
             inplace = True)


log_function \
    .DebugReturnObjectWriteObject \
        (destinationDataFrame)

### **Aviation Accidents Locations Database Table**

In [14]:
locationsDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .AVIATION_ACCIDENT_LOCATIONS_CSV_FILE)

locationsDataFrame \
    .drop \
        (columns \
             = locationsDataFrame \
                .columns[0], 
         axis = 1, 
         inplace = True)


log_function \
    .DebugReturnObjectWriteObject \
        (locationsDataFrame)

### **Aviation Accidents Narratives Database Table**

In [15]:
narrativesDataFrame \
    = function. \
        ReturnCSVFileAsDataFrame \
            (local_constant \
                 .AVIATION_UPDATED_ACCIDENTS_NARRATIVE_CSV_FILE)

narrativesDataFrame \
    .drop \
        (columns \
             = narrativesDataFrame \
                .columns[0], 
         axis = 1, 
         inplace = True)


log_function \
    .DebugReturnObjectWriteObject \
        (narrativesDataFrame)

## **Section1.2: Display DataFrames**

### **Aviation Accidents Database Table**

In [16]:
captionString \
    = 'Table 1.1: Aviation Accidents (1970-2022) Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (accidentsDataFrame.head(5), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Country Database Table**

In [17]:
captionString \
    = 'Table 1.2: Country Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (countryDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Aircraft Types Database Table**

In [18]:
captionString \
    = 'Table 1.3: Aircraft Types Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (typesDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Aircraft Operators Database Table**

In [19]:
captionString \
    = 'Table 1.4: Aircraft Operators Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (operatorsDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Aircraft Damage Database Table**

In [20]:
captionString \
    = 'Table 1.5: Aircraft Damage Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (damageDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Flight Phase Database Table**

In [21]:
captionString \
    = 'Table 1.6: Flight Phase Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (phaseDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Nature of Flight Database Table**

In [22]:
captionString \
    = 'Table 1.7: Nature of Flight Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (natureDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Airports Database Table**

In [23]:
captionString \
    = 'Table 1.8: Airports Database Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (airportsDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Departure Airports Database Table**

In [24]:
captionString \
    = 'Table 1.9: Departure Airports (1970-2022) Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (departureDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Destination Airports Database Table**

In [25]:
captionString \
    = 'Table 1.10: Destination Airports (1970-2022) Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (destinationDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Aviation Accidents Locations Database Table**

In [26]:
captionString \
    = 'Table 1.11: Aviation Accidents Locations (1970-2022) Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (locationsDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

### **Aviation Accidents Narratives Database Table**

In [27]:
captionString \
    = 'Table 1.12: Aviation Accidents Narratives (1970-2022) Table'

currentStylerObject \
    = function \
        .ReturnStylerObjectStandardFormat \
            (narrativesDataFrame.head(12), 
             captionString)


log_function \
    .ReturnStylerObjectSavePNGImage \
        (currentStylerObject,
         captionString)

# <br> **Section 2: Load SQLite Database**

## **2.1: Aviation Accidents Database Table**

In [28]:
connectionSQLiteConnectionObject \
    = sqlite3.connect \
        (local_constant.SQLITE_DATABASE_PATH)




accidentsDataFrame \
    .to_sql \
        (name = 'accidents', 
         con = connectionSQLiteConnectionObject, 
         if_exists='replace',
         index = False,
         dtype = {'accident_id': 'VARCHAR PRIMARY KEY',
                  'date': 'VARCHAR NOT NULL',
                  'year': 'INTEGER NOT NULL',
                  'type': 'VARCHAR NOT NULL',
                  'operator': 'VARCHAR NOT NULL',
                  'fatalities': 'INTEGER NOT NULL',
                  'occupants': 'INTEGER NOT NULL',
                  'damage': 'VARCHAR NOT NULL',
                  'phase': 'VARCHAR NOT NULL',
                  'nature': 'VARCHAR NOT NULL',
                  'departure': 'VARCHAR NOT NULL',
                  'destination': 'VARCHAR NOT NULL',
                  'location': 'VARCHAR NOT NULL',
                  'city': 'VARCHAR NOT NULL',
                  'state': 'VARCHAR',
                  'country': 'VARCHAR NOT NULL',
                  'country_code': 'VARCHAR NOT NULL',
                  'lat': 'REAL NOT NULL',
                  'lon': 'REAL NOT NULL',
                  'narrative': 'TEXT'})

838

## **2.2: Country Database Table**

In [29]:
countryDataFrame \
    .to_sql \
        ('country', 
         con = connectionSQLiteConnectionObject, 
         if_exists='replace', 
         index = False, 
         dtype = {'id_number': 'INTEGER PRIMARY KEY',
                  'country': 'VARCHAR NOT NULL',
                  'country_code': 'VARCHAR NOT NULL',
                  'country_code3': 'VARCHAR NOT NULL',
                  'capital': 'VARCHAR NOT NULL',
                  'region': 'VARCHAR NOT NULL',
                  'subregion': 'VARCHAR NOT NULL',
                  'lat': 'REAL NOT NULL',
                  'lon': 'REAL NOT NULL'})

229

## **2.3: Aircraft Types Database Table**

In [30]:
#typesDataFrame \
#    .to_sql \
#        ('types', 
#         con = connectionSQLiteConnectionObject, 
#         if_exists='replace', 
#         index = False, 
#         dtype = {'id_number': 'INTEGER PRIMARY KEY',
#                  'types': 'VARCHAR NOT NULL'})

## **2.4: Aircraft Operators Database Table**

In [31]:
#operatorsDataFrame \
#    .to_sql \
#        ('operators', 
#         con = connectionSQLiteConnectionObject, 
#         if_exists='replace', 
#         index = False, 
#         dtype = {'id_number': 'INTEGER PRIMARY KEY',
#                  'operators': 'VARCHAR NOT NULL'})

## **2.5: Aircraft Damage Database Table**

In [32]:
#damageDataFrame \
#    .to_sql \
#        ('damage', 
#         con = connectionSQLiteConnectionObject, 
#         if_exists='replace', 
#         index = False, 
#         dtype = {'id_number': 'INTEGER PRIMARY KEY',
#                  'damage': 'VARCHAR NOT NULL'})

## **2.6: Flight Phase Database Table**

In [33]:
#phaseDataFrame \
#    .to_sql \
#        ('phase', 
#         con = connectionSQLiteConnectionObject, 
#         if_exists='replace', 
#         index = False,
#         dtype = {'id_number': 'INTEGER PRIMARY KEY',
#                  'phase': 'VARCHAR NOT NULL'})

## **2.7: Nature of Flight Database Table**

In [34]:
#natureDataFrame \
#    .to_sql \
#        ('nature', 
#         con = connectionSQLiteConnectionObject, 
#         if_exists='replace', 
#         index = False, 
#         dtype = {'id_number': 'INTEGER PRIMARY KEY',
#                  'nature': 'VARCHAR NOT NULL'})

## **2.8: Airports Database Table**

In [35]:
airportsDataFrame \
    ['id_number'] \
        = airportsDataFrame \
            .index

airportsDataFrame \
    .to_sql \
        ('airports', 
         con = connectionSQLiteConnectionObject, 
         if_exists='replace', 
         index = False, 
         dtype = {'id_number': 'INTEGER PRIMARY KEY',
                  'icao': 'VARCHAR NOT NULL',
                  'iata': 'VARCHAR NOT NULL',
                  'name': 'VARCHAR NOT NULL',
                  'state': 'VARCHAR',
                  'country': 'VARCHAR NOT NULL',
                  'country_code': 'VARCHAR NOT NULL',
                  'lat': 'REAL NOT NULL',
                  'lon': 'REAL NOT NULL'})

1055

## **2.9: Departure Airports Database Table**

In [36]:
departureDataFrame \
    .to_sql \
        ('departure', 
         con = connectionSQLiteConnectionObject, 
         if_exists='replace', 
         index = False, 
         dtype = {'accident_id': 'VARCHAR PRIMARY KEY',
                  'date': 'VARCHAR NOT NULL',
                  'year': 'INTEGER NOT NULL',
                  'icao': 'VARCHAR NOT NULL',
                  'iata': 'VARCHAR NOT NULL',
                  'name': 'VARCHAR NOT NULL',
                  'state': 'VARCHAR',
                  'country': 'VARCHAR NOT NULL',
                  'country_code': 'VARCHAR NOT NULL',
                  'lat': 'REAL NOT NULL',
                  'lon': 'REAL NOT NULL'})

838

## **2.10: Destination Airports Database Table**

In [37]:
destinationDataFrame \
    .to_sql \
        ('destination', 
         con = connectionSQLiteConnectionObject, 
         if_exists='replace', 
         index = False, 
         dtype = {'accident_id': 'VARCHAR PRIMARY KEY',
                  'date': 'VARCHAR NOT NULL',
                  'year': 'INTEGER NOT NULL',
                  'icao': 'VARCHAR NOT NULL',
                  'iata': 'VARCHAR NOT NULL',
                  'name': 'VARCHAR NOT NULL',
                  'state': 'VARCHAR',
                  'country': 'VARCHAR NOT NULL',
                  'country_code': 'VARCHAR NOT NULL',
                  'lat': 'REAL NOT NULL',
                  'lon': 'REAL NOT NULL'})

838

## **2.11: Aviation Accidents Locations Database Table**

In [38]:
locationsDataFrame \
    ['country_code'] \
        .fillna \
            ('NA', 
             inplace = True)

In [39]:
#locationsDataFrame \
#    .to_sql \
#        ('locations', 
#         con = connectionSQLiteConnectionObject, 
#         if_exists='replace', 
#         index = False, 
#         dtype = {'accident_id': 'VARCHAR PRIMARY KEY',
#                  'icao': 'VARCHAR NOT NULL',
#                  'iata': 'VARCHAR NOT NULL',
#                  'name': 'VARCHAR NOT NULL',
#                  'state': 'VARCHAR',
#                  'country': 'VARCHAR NOT NULL',
#                  'country_code': 'VARCHAR NOT NULL',
#                  'lat': 'REAL NOT NULL',
#                  'lon': 'REAL NOT NULL'})

## **2.12: Aviation Accidents Narratives Database Table**

In [40]:
#narrativesDataFrame \
#    .to_sql \
#        ('narratives', 
#         con = connectionSQLiteConnectionObject, 
#         if_exists='replace', 
#         index = False, 
#         dtype = {'accident_id': 'VARCHAR PRIMARY KEY',
#                  'narrative': 'VARCHAR'})

# Section 3: SQLite Database Check

## **3.1: Check Database Tables

In [41]:
# This line of code generates the engine for the SQLite database.
engineSQLAlchemyEngineObject \
    = create_engine \
        (local_constant.SQLITE_DATABASE)


# This line of code sets up an existing database schema for reflection 
# into a new model.
baseSQLAlchemyDeclarativeMetaObject \
    = automap_base()


# This line of code reflects the database tables.
baseSQLAlchemyDeclarativeMetaObject \
    .prepare \
        (engineSQLAlchemyEngineObject, 
         reflect \
             = True)

# These lines of code save the references to the required database 
# tables.
accidentsSQLAlchemyDeclarativeMetaObject \
    = baseSQLAlchemyDeclarativeMetaObject \
        .classes \
            .accidents

departureDeclarativeMetaObject \
    = baseSQLAlchemyDeclarativeMetaObject \
        .classes \
            .departure

departureDeclarativeMetaObject \
    = baseSQLAlchemyDeclarativeMetaObject \
        .classes \
            .destination

In [42]:
# This line of code views all of the classes that the SQLAlchemy's
# function, automap, found.
baseSQLAlchemyDeclarativeMetaObject \
    .classes.keys()

['accidents', 'airports', 'country', 'departure', 'destination']

## **3.2: Close Database Connections

In [43]:
connectionSQLiteConnectionObject \
    .close()

In [44]:
engineSQLAlchemyEngineObject \
    .dispose()

In [45]:
#log_subroutine \
#    .EndProgramExecution()